language: node_js
node_js:
  - "8"
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
  npm
# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm i
script:
  - npm test


# language: node_js
# node_js:
#   - "8"
# dist: trusty
# sudo: false
# addons:
#   chrome: stable
# before_install:
#   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
# cache:
#   directories:
#     - node_modules
# install:
#   - npm i
# script:
#   - npm test
